steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build' 
      - '-t' 
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/abc/test'
      - '--build-arg'
      - 'projectid=$PROJECT_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/abc/test'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'gcloud'
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'test'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/abc/test'
      - '--region'
      - 'asia-northeast1'
      - '--max-retries'
      - '0'
